# ekf.yaml

ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: chassis
    world_frame: odom

    # Subscribe to wheel odometry
    odometry0: /odom
    odometry0_config: [true,  true,  false,  # x, y, z
                       false, false, true,  # roll, pitch, yaw
                       true,  true,  false, # x_dot, y_dot, z_dot
                       false, false, true,  # roll_dot, pitch_dot, yaw_dot
                       false, false, false] # x_acc, y_acc, z_acc
    odometry0_differential: false
    odometry0_relative: false
